

name: Auto Label in Issue
description: 'Add the same tag of the issue associated with the pull_request.'
author: 'Yaminyam'
inputs:
  repo-token:
    description: 'A token for the repository'
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'user-plus'
  color: 'red'
